import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import NoticeStrip from "@/components/notice_strip/noticeStrip";
import Navbar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/ScrollToTop/ScrollToTop";
import WhatsAppWidget from "@/components/WhatasppWidget/WhatsAppWidget";


const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Divine Institute of Management and Technology", // Fixed a slight typo in Management here!
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // FIX 1: Added 'overflow-x-hidden' to the HTML tag
      className={cn("h-full", "antialiased", "overflow-x-hidden", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      {/* FIX 2: Added 'overflow-x-hidden' to the body tag */}
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <NoticeStrip/>
        <Navbar/>
        
        {/* Main content wrapper */}
        <main className="flex-1">
          {children}
        </main>
        
        <Footer/>
        <WhatsAppWidget/>
        <ScrollToTop/>
      </body>
    </html>
  );
}